project:
  type: book

book:
  title: "Josiah's Remote Sensing Learning Diary"
  # author: "Josiah Tan"
  navbar:
    collapse: true
    collapse-below: lg
    background: light
    #reader-mode: true
    search: true
    right:
      - icon: github
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - references.qmd
  favicon: "img/favicon.ico"

bibliography: references.bib
#csl: harvard-cite-them-right.csl

format:
  html:
    theme:
        light: [cosmo, flatly]
        dark: [cosmo, darkly]
    cite-method: citeproc
  pdf:
    documentclass: scrreprt

editor: visual

