# Preface {.unnumbered}

This is a Quarto book about Josiah's learning journey in the world of Remote Sensing. It will be updated weekly with a summary of what I've learnt through the CASA0023 Remote Sensing module with my thoughts on how it can be applied in different contexts.

# Self-Introduction

Welcome to my learning diary on remote sensing! I am currently a MSc Urban Spatial Science student at UCL Centre for Advanced Spatial Analytics (CASA). Prior to this, I graduated from UCL with a BSc in Geography with Economics. I am mainly interested in using spatial analysis techniques to urban problems from a policymaking perspective, which explains why I am at CASA now. After graduation, I will be working with Housing Development Board (HDB) in Singapore, the key agency responsible for public housing in the country. I have also interned with Singapore's Ministry of Sustainability and Environment before, and am interested in urban environmental issues. Before my undergraduate studies, I also had a brief stint in the Singapore Armed Forces Mapping Unit where I had some exposure to satellite imagery and digitizing maps. I hope to learn necessary and relevant skills and techniques that can be applied to both urban housing and environmental contexts.
