# Week 8: Temperature and Policy

---
title: "Week 8: Temperature and Policy"
editor: visual
---

## Learning Objectives

-   Analysing temperature across urban areas

    -   Along both spatial and time scales

## Summary of Key Concepts

### Urban Heat Island

Urban areas are of higher temperatures

2 main factors:

-   More dark surfaces that retain heat

-   Less vegetation cooling the environment

Other factors:

-   Low Sky View Factor

-   Air speed, cloud cover, cyclic solar radiation, building material and athropogenic energy

**Cost of Urban Heat**:

-   **Social**

-   **Environmental**

    -   Positive feedback loop

-   **Economic**

    -   Only Melbourne has assessed the cost of Urban Heat Island effect before

    -   UHI not really included in climate prediction models (Estrada et al 2017)

**Global Policy Documents/ Goals related to UHI**

-   New Urban Agenda

-   Sustainable Development Goals (SDGs)

-   COP26

### **Resources**

#### Beat the Heat Handbook Case Studies

**Superblocks**

**Medellin Green Corridors**

**Turn Down the Heat Strategy and Action Plan**

**Chicago 1995 Heatwave**

#### Metropolitan UHI Reduction Strategies

**London Plan**

**Singapore Master Plan**

-   While the document..

## Summary of Practical Content

This week's practical focuses on extracting temperature data from satellite data, and creating outputs that analyse it in spatial and time scales.

### Methodology to extract temperature per spatial unit

-   Spatial data

-   Temperature datasets (MODIS, Landsat etc)

    -   collection

    -   filter for standard stuff

-   Zonal statistics

-   output shapefile

### Mean Radiant Temperature

## Application of Key Concepts and Skills

## Reflections

How achievable are these policy suggestions at various scales?
